FROM arm64v8/ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    gfortran \
    gcc \
    g++ \
    openmpi-bin \
    openmpi-common \
    libopenmpi-dev \
    make \
    wget \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*