FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        autoconf=2.71-2 \
        g++ \
        gcc \
        gfortran \
        git \
        libopenmpi-dev \
        make \
        openmpi-bin \
    && rm -rf /var/lib/apt/lists/*
